### ISSUE TITLE
Comment on "Managing Design Documents"

### ISSUE THREAD

**Issue by nomicode** [oreilly/couchdb-guide#1]
> If you merely want to peruse the source code while reading along with the=
>  book, it is available as standard zip or tar downloads. To get the zip ver=
> sion access the following URL from your browser, which will redirect to the=
>  latest zip file of Sofa. If you prefer, a tar file is available as well.

Wrong link targets: Links points to couchapp instead of sofa

**Comment by janl** [comment]
fix link to sofa. Closed by 6655a9529c1efa1019d618e24ad4fe217841b925
