### ISSUE TITLE
Comment on "Managing Design Documents"

### ISSUE THREAD

**Issue by nomicode** [oreilly/couchdb-guide#2]
> With this file set up, you can push your CouchApp with the command coucha=
> pp push, which will push the application to the "default" database. CouchAp=
> p also supports alternate environments. To push your application to a devel=
> opment database, you could use couchapp push dev. In our experience, taking=
>  the time to setup a good .couchapprc is always worth it. Another benefit i=
> s that it keeps your passwords off the screen when you are working.

Note that JSON syntax uses commas as separators only. Trailing commas
will cause your push to fail!

**Comment by janl** [comment]
add note about trailing commas in JSON. Closed by ceb4e80793cb9387606f019f4bbb8bf1dbba4ac0
