### ISSUE TITLE
Admonition blocks

### ISSUE THREAD

**Issue by nomicode** [oreilly/couchdb-guide#277]
The lines above and bellow the admonition blocks look a bit weird when they appear next to a pre block or a title. I wonder if they should loose the borders, or if something else could be used to make them stand out a bit. When I first thought about how it would look on this site, I thought about a little ribbon wrapping from "behind" the page with an icon on it. That might be too complex though.

**Comment by Kriesse** [comment]
Agreed. I pushed a prettier, ribbon-like style. This is not perfectly flexible though – when an aside gets longer (higher) than 750 px, it looks a bit off (border on bottom left disappears). But as this i unlikely to happen, I think we can live with that. (Solution would be extra markup or an even bigger background image).
