### ISSUE TITLE
Redirect from old book is not working

### ISSUE THREAD

**Issue by nomicode** [oreilly/couchdb-guide#285]
http://books.couchdb.org/relax/ goes to http://guide.couchdb.org/relax/

**Comment by janl** [comment]
book[s].couchdb.[com|net|org]/\* should now redirect to http://guide.couchdb.org/

Leaving open since I want all old URLs to redirect to the new ones.

**Comment by janl** [comment]
All old URLS should now point to new counterparts. /relax/ points to http://guide.couchdb.org/ all other (404) urls too.

**Comment by janl** [comment]
Clarification, the old URLS point to the draft version of the book for most up to date content (a request by @jchris)
