### ISSUE TITLE
The Core API

### ISSUE THREAD

**Issue by jcdevilla** [oreilly/couchdb-guide#292]
Typo here. The curl command has --data-binary for its option, but the paragraph directly following it states "-d@".

>    curl -vX PUT http://127.0.0.1:5984/albums/6e1295ed6c29495e54cc05947f18c8af/ artwork.jpg?rev=2-2739352689 --data-binary @artwork.jpg -H "Content-Type: image/jpg"
> 
> The -d@ option tells curl to read a file’s contents into the HTTP request body.

**Comment by janl** [comment]
clarification. Closed by eafc3676ae0324c6e87a3d80b679c802f1da9d19
