### ISSUE TITLE
Confusion in tour.html

### ISSUE THREAD

**Issue by magiconair** [oreilly/couchdb-guide#294]
I think the 2nd value in this paragraph should be 127.0.0.1 and not http://127.0.0.1:5984/_utils as the problem describes the replication to fail when the server is accessed via localhost. 

It is probably both correct but it can be interpreted as replacing localhost with a full URL.

<p>Some common network configurations cause the replication test to fail when accessed via the <code>localhost</code> address. You can fix this by accessing CouchDB via <em>http://127.0.0.1:5984/_utils/</em>.

Frank

**Comment by janl** [comment]
Clarify note, fix markup. Closed by d209771a60e6cc6f9cc2340505762a90b3164f90.
