### ISSUE TITLE
"Comment_On": "Change Notifications", "reason": "small spelling  fixes"

### ISSUE THREAD

**Issue by nomicode** [oreilly/couchdb-guide#3]
> The req parameter of the filter function includes a member userCtx, the u=
> ser context. It includes information about the user that already has been a=
> uthenticated over HTTP earlier in the phase of the request. Specifically re=
> q.userCtx.name includes the user name of the user that _made_ the filtered =
> changes request. We can be sure that the user is who he says he is because =
> he _has been_ authenticated against one of the authenticating schemes in Co=
> uchDB. With this, we don=92t even need the dynamic filter parameter (althou=
> gh it can still be useful in other situations).

**Comment by janl** [comment]
what needs changing here?

**Comment by janl** [comment]
fixed in PR
