### ISSUE TITLE
_session needs "name", but book says "username"

### ISSUE THREAD

**Issue by BigBlueHat** [oreilly/couchdb-guide#310]
http://guide.couchdb.org/draft/security.html#cookies

This page has a sample curl line that says:

<pre>
> HOST="http://127.0.0.1:5984"
> curl -vX POST $HOST/_session -H 'application/x-www-form-urlencoded'
-d 'username=anna&password=secret'
</pre>

It should say:

<pre>
> HOST="http://127.0.0.1:5984"
> curl -vX POST $HOST/_session -H 'application/x-www-form-urlencoded'
-d 'name=anna&password=secret'
</pre>

Thanks!

**Comment by shadowmint** [comment]
Its strange this issue doesn't turn up in the list unless you search for it. It's not marked as closed is it?

**Comment by rnewson** [comment]
Bump. This is still an issue.

**Comment by janl** [comment]
s/username/name. Closed by 3509febff0658c1f0cb3c1c3218970e3d1b35eb0
