### ISSUE TITLE
http://guide.couchdb.org/draft/api.html#replication

### ISSUE THREAD

**Issue by fisherwebdev** [oreilly/couchdb-guide#328]
The curl commands for replication are inaccurate for the current version of CouchDB.  

curl -vX POST http://127.0.0.1:5984/_replicate -d '{"source":"albums","target":"albums-replica"}'

should be

curl -vX POST http://127.0.0.1:5984/_replicate -d '{"source":"albums","target":"albums-replica"}' -H "Content-Type: application/json"

**Comment by janl** [comment]
fuxed
