### ISSUE TITLE
Update tour to reflect version 1.0.

### ISSUE THREAD

**Issue by bradh** [oreilly/couchdb-guide#371]
The draft/tour.html chapter reflects 0.10, but there are some changes in the latest version.

<pre><code>
From 794d6ac70deb757bce85d9fbe14b6edc69b0bac1 Mon Sep 17 00:00:00 2001
From: Brad Hards <bradh@frogmouth.net>
Date: Fri, 4 Feb 2011 14:32:13 +1100
Subject: [PATCH] Tour: Update to reflect version 1.0.x

We now have "_users" database, and this patch mainly addresses that. It also changes some wording to be
a bit more neutral.

---
 draft/tour.html |   20 ++++++++++----------
 1 files changed, 10 insertions(+), 10 deletions(-)

diff --git a/draft/tour.html b/draft/tour.html
index 9220731..f4cc916 100644
--- a/draft/tour.html
+++ b/draft/tour.html
@@ -29,7 +29,7 @@ curl http://127.0.0.1:5984/
 <p>The reply should look something like:
 
 <pre>
-{"couchdb":"Welcome","version":"0.10.1"}
+{"couchdb":"Welcome","version":"1.0.2"}
 </pre>
 

 <p>Not all that spectacular. CouchDB is saying “hello” with the running version number.
@@ -45,10 +45,10 @@ curl -X GET http://127.0.0.1:5984/_all_dbs
 <p>The response should look like:

 <pre>
-[]
+["_users"]
 </pre>

-<p>Oh, that’s right, we didn’t create any databases yet! All we see is an empty list.
+<p>So we have one database (in this case an internal database used for authentication, which is covered in the<a href="security.html">Security Chapter</a>.

 <div class="aside note">

@@ -70,19 +70,19 @@ curl -X PUT http://127.0.0.1:5984/baseball
 {"ok":true}
 </pre>

-<p>Retrieving the list of databases again shows some useful results this time:
+<p>Retrieving the list of databases again shows our new baseball database, in addition to the internal database we saw previously:

 <pre>
 curl -X GET http://127.0.0.1:5984/_all_dbs
 </pre>

 <pre>
-["baseball"]
+["_users","baseball"]
 </pre>

 <div class="aside note">

-<p>We should mention <em>JavaScript Object Notation (JSON)</em> here, the data format CouchDB speaks. JSON is a lightweight data interchange format based on JavaScript syntax. Because JSON is natively compatible with JavaScript, your web browser is an ideal client for CouchDB.
+<p>We should mention <em>JavaScript Object Notation (JSON)</em> here, the data format that CouchDB uses. JSON is a lightweight data interchange format based on JavaScript syntax. Because JSON is natively compatible with JavaScript, your web browser is an ideal client for CouchDB.

 <p>Brackets (<code>[]</code>) represent ordered lists, and curly braces (<code>{}</code>) represent key/value dictionaries. Keys must be strings, delimited by quotes (<code>"</code>), and values can be strings, numbers, booleans, lists, or key/value dictionaries. For a more detailed description of JSON, see <a href="json.html">Appendix E, JSON Primer</a>.

@@ -121,7 +121,7 @@ curl -X GET http://127.0.0.1:5984/_all_dbs
 <p>CouchDB will respond with:

 <pre>
-["baseball", "plankton"]
+["_users","baseball","plankton"]
 </pre>

 <p>To round things off, let’s delete the second database:
@@ -145,7 +145,7 @@ curl -X GET http://127.0.0.1:5984/_all_dbs
 <p>CouchDB will respond with:

 <pre>
-["baseball"]
+["_users","baseball"]
 </pre>

 <p>For brevity, we’ll skip working with documents, as the next section covers a different and potentially easier way of working with CouchDB that should provide experience with this. As we work through the example, keep in mind that “under the hood” everything is being done by the application exactly as you have been doing here manually. Everything is done using <code>GET</code>, <code>PUT</code>, <code>POST</code>, and <code>DELETE</code> with a URI.
@@ -162,7 +162,7 @@ http://127.0.0.1:5984/_utils/

 <p>If you’re running version 0.9 or later, you should see something similar to <a href="#figure/1">Figure 1, “The Futon welcome screen”</a>. In later chapters, we’ll focus on using CouchDB from server-side languages such as Ruby and Python. As such, this chapter is a great opportunity to showcase an example of natively serving up a dynamic web application using nothing more than CouchDB’s integrated web server, something you may wish to do with your own applications.

-<p>The first thing we should do with a fresh installation of CouchDB is run the test suite to verify that everything is working properly. This assures us that any problems we may run into aren’t due to bothersome issues with our setup. By the same token, failures in the Futon test suite are a red flag, telling us to double-check our installation before attempting to use a potentially broken database server, saving us the confusion when nothing seems to be working quite like we expect!
+<p>The first thing we should do with a fresh installation of CouchDB is run the test suite to verify that everything is working properly. This assures us that any problems we may run into are not due to bothersome issues with our setup. By the same token, failures in the Futon test suite are a red flag, telling us to double-check our installation before attempting to use a potentially broken database server, saving us the confusion when nothing seems to be working quite like we expect!

 <div class="figure" id="figure/1">

@@ -178,7 +178,7 @@ http://127.0.0.1:5984/_utils/

 </div>

-<p>Navigate to the test suite by clicking “Test Suite” on the Futon sidebar, then click “run all” at the top to kick things off. <a href="#figure/2">Figure 2, “The Futon test suite running some tests”</a> shows the Futon test suite running some tests.
+<p>Navigate to the test suite by clicking “Test Suite” on the Futon sidebar, then click “run all” at the top to start the test suite. <a href="#figure/2">Figure 2, “The Futon test suite running some tests”</a> shows the Futon test suite running some tests.

 <div class="figure" id="figure/2">
## 

1.7.1

<code/><pre/>

**Comment by denisw** [comment]
I also stumbled over this problem. In fact, now there is also a `_replicator` database after install, so

```
curl http://127.0.0.1:5984/
```

now returns

```
["_replicator","_users"]
```

I am not sure how to properly fix this, though, as neither of the two databases are discussed in the guide right now. It is kind of awkward that there is no place in the book to point to, should the user want to know what these databases are about. However, as a temporary solution, one could refer to the official CouchDB documentation.
