### ISSUE TITLE
Curl options

### ISSUE THREAD

**Issue by kravietz** [oreilly/couchdb-guide#379]
This example:

curl -X POST http://127.0.0.1:5984/basic -d '{}'

won't work because CouchDB will reply that Content-Type must be application/json. Solution is to add -H "Content-Type: application/json" option. Also the single quotation marks (') will not work on Windows, so I suggest replacing them with double quotes (").

**Comment by kmpm** [comment]
I can only agree. I found this in the chapter "Design Documents"
changing it to 

curl -X POST http://127.0.0.1:5984/basic -H "Content-Type: application/json" -d "{}"

would solve the issue

**Comment by janl** [comment]
Yup, as the book preface states, it documents the (now ancient) 0.8 and all examples need to be updated to reflect the new content-type requirement

**Comment by janl** [comment]
and fixed.
