### ISSUE TITLE
SQL cookbook

### ISSUE THREAD

**Issue by arashbi** [oreilly/couchdb-guide#384]
In this function: 
function(doc) {
  if(doc["mime-type"]) {
    // from the start (^) match everything that is not a slash ([^\/]+) until
    // we find a slash (\/). Slashes needs to be escaped with a backslash (\/)
    var prefix = doc["mime-type"].match(/^[^\/]+\//);
    if(prefix) {
      emit(prefix, null);
    }
  }
}

I think the correct emit should be emit(prefix,doc) not profic,null

**Comment by janl** [comment]
nope, the value can be anything, I chose null :)
