### ISSUE TITLE
extra space in curl command in The Core API

### ISSUE THREAD

**Issue by rossdavidh** [oreilly/couchdb-guide#386]
When trying the example for attachments, in this case an image upload, the curl command given is:

> curl -vX PUT http://127.0.0.1:5984/albums/6e1295ed6c29495e54cc05947f18c8af/ artwork.jpg?rev=2-2739352689 --data-binary @artwork.jpg -H "Content-Type: image/jpg"

This has a space between the document id and "artwork.jpg", which if you copy and paste into the command line will cause an error:

> curl: (6) Couldn't resolve host 'artwork.jpg'

Removing this space makes it work correctly.  Thanks for the great book by the way!

**Comment by janl** [comment]
fixed
