### ISSUE TITLE
Fix in "A basic design document"

### ISSUE THREAD

**Issue by linuxnow** [oreilly/couchdb-guide#415]
Rhe second instruction is wrong:

curl -X PUT http://127.0.0.1:5984/basic
curl -X PUT http://127.0.0.1:5984/basic/_design/example -data-binarymydesign.json

It should be with double dash and @:
curl -X PUT http://127.0.0.1:5984/basic/_design/example --data-binary @mydesign.json

**Comment by pulkitsinghal** [comment]
I vote for this too, I noticed the same issue in the instructions on this page:
http://guide.couchdb.org/draft/design.html

**Comment by pulkitsinghal** [comment]
Same as #422

**Comment by michaelabon** [comment]
Fixed in #428. Thanks for the dupe catch, @pulkitsinghal.

**Comment by max-giro** [comment]
I can still find this issue in both online 1st Ed and draft.

**Comment by michaelabon** [comment]
That's because my PR is still open. There's a PR from June still open.

**Comment by farser** [comment]
Yep.  Me too.

Thanks to the @Euroside (http://euroside.wordpress.com/2011/12/08/couchdb-definitive-guide-chapter-6-companion/) for expanding on that section of the book and for providing this noob with the correct command.

**Comment by janl** [comment]
resolved

**Comment by ghost** [comment]
This is still online FYI

**Comment by michaelabon** [comment]
The [draft version](http://guide.couchdb.org/draft/design.html#basic) of the book shows it fixed, @w0lfe. Maybe you are looking at the [1st edition](http://guide.couchdb.org/editions/1/en/design.html#basic)? You are likely not going to find that updated.

**Comment by ghost** [comment]
Yeah 1st ed, so the draft version is the one that is kept updated?

**Comment by michaelabon** [comment]
That appears to be the case. The draft version does say that it accepts pull requests and welcomes issues.

**Comment by janl** [comment]
Applied to ed1.
