### ISSUE TITLE
Faulty Curl: "curl -X PUT http://127.0.0.1:5984/basic/_design/example -data-binarymydesign.json"

### ISSUE THREAD

**Issue by Michael-Zinn** [oreilly/couchdb-guide#422]
Part II Section "A Basic Design Document" has this faulty curl:
curl -X PUT http://127.0.0.1:5984/basic/_design/example -data-binarymydesign.json

It should be like this instead:
curl -X PUT http://127.0.0.1:5984/basic/_design/example --data-binary @mydesign.json

**Comment by michaelabon** [comment]
Thanks for this, @RedNifre. I figured out the double-hyphen and the spacing issue myself, but the at symbol eluded me.

**Comment by pulkitsinghal** [comment]
Same as #415

**Comment by franklinharper** [comment]
I ran into this problem too.

**Comment by janl** [comment]
resolved.
