### ISSUE TITLE
list functions

### ISSUE THREAD

**Issue by sakoht** [oreilly/couchdb-guide#453]
This page:
http://guide.couchdb.org/draft/transforming.html

Gets right into a very complicated example of using a list function, but hasn't given the simple version.

It needs the "hello world" for rendering a very simple set of documents returned by a view.  The "J. Chris got excited about the idea of using list functions to generate config..." is a very secondary example.

Much of the book has this problem.  It's written by experts to document subtleties, but their noses are too close to the problem, and the basics are forgotten.

**Comment by janl** [comment]
Wanna help and submit a pull request with a simple hello world?

**Comment by sakoht** [comment]
It's been a bit since I looked at it but sure I'll give it a hack. :)

**Comment by sakoht** [comment]
I just sent a pull request.  Good luck with the book!
