### ISSUE TITLE
Uploading a Design Document

### ISSUE THREAD

**Issue by wraithmonster** [oreilly/couchdb-guide#454]
Towards the bottom of the page http://guide.couchdb.org/draft/design.html, the syntax for uploading the design doc is wrong. 

`curl -X PUT http://127.0.0.1:5984/basic/_design/example -data-binarymydesign.json`

should be 

`curl -X PUT http://127.0.0.1:5984/basic/_design/example -d @mydesign.json` 

as noted here http://stackoverflow.com/a/4418695/154065.

**Comment by andygold99** [comment]
I also found that curl -X PUT http://127.0.0.1:5984/basic/_design/example --data-binary "@mydesign.json" works, but wraithmonster's suggestion seems easier to type and remember.

**Comment by janl** [comment]
This has been fixed for a while in draft/

-d can lead to issues with larger files, hence our use of --data-binary.

**Comment by wraithmonster** [comment]
There's still a typo though. 

`-data-binarymydesign.json` should be `--data-binary @mydesign.json`.

**Comment by janl** [comment]
Where is that typo? If possible, please point to the source file :)

**Comment by wraithmonster** [comment]
My mistake - it is fixed now at the source. Thanks!

**Comment by janl** [comment]
No worries, thanks for the report. It should show up on the site as well (github pages ftw), make sure to clear your cache before reloading the page. I could get the latest Safari to shift-reload earlier.
