### ISSUE TITLE
SSL now available built-in

### ISSUE THREAD

**Issue by avimar** [oreilly/couchdb-guide#464]
http://guide.couchdb.org/draft/security.html#security

> We suggest you read up on VPNs and setting up CouchDB behind an HTTP proxy
> (like Apache httpd’s mod_proxy, nginx, or varnish) that will handle SSL for you.
> CouchDB does not support exposing its API via SSL at the moment.
> It can, however, replicate with other CouchDB instances that are behind an SSL proxy.

This is no longer true, it's built-in now:
http://wiki.apache.org/couchdb/How_to_enable_SSL

**Comment by sghill** [comment]
It looks like this is fixed with @janl's commit. Can we close it?
