### ISSUE TITLE
Comment on ""

### ISSUE THREAD

**Issue by nomicode** [oreilly/couchdb-guide#5]
"hosts" should be "host's"

From http://books.couchdb.org/relax/design-documents/lists

> Now that we=92ve rendered and sent the file=92s head, it=92s time to star=
> t rendering the list itself. Each list item will be the result of convertin=
> g a view row to a virtual hosts configuration element. The first thing we d=
> o is call getRow() to get a row of the view.

**Comment by janl** [comment]
Fixed in proofreading
