### ISSUE TITLE
Cloning blog application with couchapp doesn't work

### ISSUE THREAD

**Issue by martasd** [oreilly/couchdb-guide#501]
http://jchrisa.net/drl/_design/sofa referenced in http://guide.couchdb.org/draft/managing.html is down.

**Comment by cadamez** [comment]
Cloning from http://jchris.ic.ht/drl/_design/sofa/ also fails with this error:
`2015-01-21 15:12:33 [CRITICAL] unknown error [socket.error: [Errno 111] Connection refused]`
