### ISSUE TITLE
Invalid JSON Error on Design Documents PUT command

### ISSUE THREAD

**Issue by Ninerian** [oreilly/couchdb-guide#503]
While working through the official guide I discovered an error on the design document part.

After executing the command:

```
curl -X PUT http://127.0.0.1:5984/basic/_design/example -data-binary @mydesign.json
```

i got the error:

```
{"error":"bad_request","reason":"invalid_json"}
curl: (6) Could not resolve host: mydesign.json
```

the debuglog told me

```
Invalid JSON: {{error,
                                     {1,
                                      "lexical error: invalid char in json text.\n"}},
                                    <<"ata-binary">>}
```

After some searching on google i discovered the solution on stackoverflow: http://stackoverflow.com/questions/2461798/error-about-invalid-json-with-couchdb-view-but-the-jsons-fine

by changing the command to

```
curl -X PUT http://127.0.0.1:5984/basic/_design/example -d @mydesign.json
```

i was able to go further in the guide.

**Comment by nkux** [comment]
thx!
