### ISSUE TITLE
Couchdb 1.5 needs to restarted very frequently

### ISSUE THREAD

**Issue by rajavarikuti** [oreilly/couchdb-guide#513]
We had installed couchdb 1.5 on one of our linux node. As along as we are connected to the node using putty , we are able to access the couchdb. If the putty is disconnected or seesion times out , couch db is not running and we need to restart the couch db every day.

We are starting the couch using 'couchdb' command and the couch starts and logs will be appering on the putty as shown below. , 

[info] [<0.14812.0>] 10.8.61.251 - - GET /login_failed_summary/RaJaS 404
[info] [<0.14812.0>] 10.8.61.251 - - GET /login_failed_summary/RaJaS 404
[info] [<0.14812.0>] 10.8.61.251 - - PUT /login_failed_summary/RaJaS 201
[info] [<0.14812.0>] 10.8.61.251 - - GET /login_failed_summary/RaJaS 200
[info] [<0.14812.0>] 10.8.61.251 - - DELETE /login_failed_summary/RaJaS?rev=1-e8                        e813f6c0cb5f1662ceab132835d2b0 200

Registry is not done , below is the output.
curl http://localhost:5984/registry
{"error":"not_found","reason":"no_db_file"}

. Please help me in solving the issue , what all to be configured

**Comment by janl** [comment]
This is the wrong place to ask for CouchDB support. Please ask again on the User List: http://couchdb.apache.org
