### ISSUE TITLE
"afrikan" should be "african" or "afrikaans"

### ISSUE THREAD

**Issue by kaapstorm** [oreilly/couchdb-guide#532]
The example given in the "[Reduce / Rereduce](http://guide.couchdb.org/draft/views.html#reduce)" section of the "Finding Your Data with Views" chapter includes a list of adjectives/cultures: `"afrikan"`; `"chinese"`; `"french"`, etc.

If these are adjectives referring to regions, i.e. Africa, China, France, etc., then the adjective for Africa would be "african". 

If they are names of cultures, then the name of an African culture that resembles "afrikan" the closest would probably be "Afrikaans".

**Comment by rnewson** [comment]
fixed in master. We did mean the language, it's a typo.

**Comment by rnewson** [comment]
https://git-wip-us.apache.org/repos/asf?p=couchdb-documentation.git;a=commitdiff;h=ce01699174dc3a5b5fb367d074f2805c00197fbd;hp=51fccc8be4a4b6e5fb8184628ef3b0e739cbfe6a

**Comment by kaapstorm** [comment]
:+1: Thank you.
