### ISSUE TITLE
Comment on "Conflict Management"

### ISSUE THREAD

**Issue by nomicode** [oreilly/couchdb-guide#85]
From http://books.couchdb.org/relax/reference/conflict-management

> Now we make a change to our document in database A and we change some oth=
> er values. See how it makes a different image for us to see the difference.=
>  It is important to not that this is still the same document. It=92s just t=
> hat there are two different revisions of that same document in each databas=
> e.

In "It is important to not that this is still the same document",
change "not" to "note"

**Comment by janl** [comment]
fixed in PR
